##  ~ UbioZur - https://github.com/UbioZur ~  ##

# Create the release.

name: Create Release

on:
  workflow_dispatch:
  repository_dispatch:
    types: [create_release-trigger]

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: release

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.run_number }}.${{ github.run_attempt }}
          files: ./*.sh
          draft: false
          prerelease: false
          make_latest: true
